name: Release - Maven Build and publish to Central

on:
  release:

jobs:
  Deploy:
    runs-on: ubuntu-latest
        
    steps:
    - name: Step 1 - Checkout release branch from GitHub
      uses: actions/checkout@v2

    - name: Step 2 - Set up JDK 1.8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'adopt'
        cache: maven

    - name: Step 3 - Verify with Maven
      run:  |
            echo "[INFO] Running with profile: signing"
            mvn --batch-mode --settings cfg/settings.xml -P signing clean verify
      env:
        OSSRH_JIRA_USERNAME: ${{ secrets.OSSRH_USERNAME }}
        OSSRH_JIRA_PASSWORD: ${{ secrets.OSSRH_TOKEN }}
        GPG_KEY_NAME: ${{ secrets.GPG_KEY_NAME }}
        GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}

    - name: Step 4 - Check Project-Version
      run:  |
            mkdir tmp/ 
            export PROJECT_VERSION=`mvn -q -Dexec.executable="echo" -Dexec.args='${project.version}' --non-recursive exec:exec` 
            tar -C tmp -xvf modules/dist.cli/target/dist.cli-${PROJECT_VERSION}.tar.gz 
            tmp/bin/cmclient --version | grep -q "^${PROJECT_VERSION}"

    - name: Step 5 - Publish package
      run: mvn --batch-mode clean deploy --settings cfg/settings.xml -P signing -DstagingProfileId=22fbc0443d9154 
      env:
        OSSRH_JIRA_USERNAME: ${{ secrets.OSSRH_USERNAME }}
        OSSRH_JIRA_PASSWORD: ${{ secrets.OSSRH_TOKEN }}
        GPG_KEY_NAME: ${{ secrets.GPG_KEY_NAME }}
        GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
     