name: CI

on:
  push:

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - name: Show Help
        uses: SAP/project-piper-action@master
        with:
          command: help