name: Maven Build and Test (Master Branch)

on: 
  push:
  pull_request:
    branches: [master, release]

jobs:
  Build:
    runs-on: ubuntu-latest

    steps:
    - name: Step 1 - Checkout main branch from GitHub
      uses: actions/checkout@v2

    - name: Step 2 - Set up JDK 1.8
      uses: actions/setup-java@v2
      with: 
        java-version: '8'
        distribution: 'adopt'
        cache: maven

    - name: maven version
      run: mvn --version

    - name: Step 3 - Verify with Maven
      uses: SAP/project-piper-action@master
      with:
        piper-version: master
        command: mavenBuild 

    - name: Step 4 - Check Project-Version
      run:  |
            mkdir tmp/ 
            export PROJECT_VERSION=`mvn -q -Dexec.executable="echo" -Dexec.args='${project.version}' --non-recursive exec:exec` 
            tar -C tmp -xvf modules/dist.cli/target/dist.cli-${PROJECT_VERSION}.tar.gz 
            tmp/bin/cmclient --version | grep -q "^${PROJECT_VERSION}"