name: Release Notes

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Define name for new Tag'
        required: true
    
jobs:
  build:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - uses: actions/setup-java@v1
        with:
          java-version: '8'

      - uses: SAP/project-piper-action@master
        name: Publish Release
        with:
          piper-version: master
          command: githubPublishRelease
          flags: --token ${{ secrets.GITHUB_TOKEN }} --version ${{ github.event.inputs.tag }} --assetPath ./piper_master