name: playground for ghActions

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Step 1 - Checkout release branch from GitHub
        uses: actions/checkout@v2

      - name: Step 2 - Set up Apache Maven Central
        uses: actions/setup-java@v1
        with: # running setup-java again overwrites the settings.xml
          java-version: 1.8
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }} # Value of the GPG private key to import
          gpg-passphrase: GPG_PASSPHRASE # env variable for GPG Passphrase