name: playground for ghActions

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Step 1 - Checkout release branch from GitHub
        uses: actions/checkout@v2

      - name: Step 2 - Set up Apache Maven Central
        uses: actions/setup-java@v1
        with: # running setup-java again overwrites the settings.xml
          java-version: 1.8
          server-id: ossrh # Value of the distributionManagement/repository/id field of the pom.xml
          server-username: OSSRH_JIRA_USERNAME # env variable for username in deploy
          server-password: OSSRH_JIRA_PASSWORD # env variable for token in deploy
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }} # Value of the GPG private key to import
          gpg-passphrase: GPG_PASSPHRASE # env variable for GPG Passphrase
        
      - name: Step 3 - Verify with Maven
        run:  |
              echo "[INFO] Running with profile: signing"
              GPG_TTY=$(tty)
              export GPG_TTY
              mvn --batch-mode -P signing clean verify
        env:
          OSSRH_JIRA_USERNAME: ${{ secrets.OSSRH_JIRA_USERNAME }}
          OSSRH_JIRA_PASSWORD: ${{ secrets.OSSRH_JIRA_PASSWORD }}
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}